### ISSUE TITLE
Can't build - T4Transform task failed

### ISSUE THREAD

**Issue by LeonTraill** [reysic/AzureKeyVaultExplorer#5]
Hello. I'm not a developer and have installed VS 2022 in order to build this for use in our workplace.

When building, I get the following error message:
![T4](https://github.com/user-attachments/assets/35b2e60c-ce21-4941-898d-63062a75fed5)

I've been using Copilot for assistance, however can't resolve this.
I've unloaded VaultLibrary and VaultExplorer to add the following line:
<T4ToolPath>C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\TextTransform.exe</T4ToolPath>

I've also added it to my PATH variable.

Bit stuck..

**Comment by reysic** [comment]
Hi @LeonTraill,

I see you've already closed this, so I'll assume you were able to successfully build the project.

Also, should you want to run Vault Explorer without building, you can visit the below URL (note that this currently points to the pre-fork version of Vault Explorer, will be updated to point to my updated version once I've configured ClickOnce deployment):
https://srnk.cc/ve
